"""Test batch re-indexing with a new document, on a copy of the production index (never the real one).

    python scripts/batch_reindex_demo.py > reports/batch_reindex.md

1. a question about electronic signatures before the update (nothing relevant exists)
2. add data/samples/batch_test_document.json (hypothetical Article 1150) → 1 chunk added and embedded
3. the same question now retrieves Article 1150
4. run the same file again → unchanged, nothing embedded (idempotent)
5. an amended version of the article → 1 chunk replaced
"""

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rag.ingest.store import collection_name, search  # noqa: E402
from rag.retrieval import Retriever  # noqa: E402

cfg = yaml.safe_load((ROOT / "params.yaml").read_text(encoding="utf-8"))
QUESTION = "Is an electronic signature on an online contract valid as evidence?"


def top3(index_dir: Path) -> str:
    name = collection_name(cfg["ingest"]["collection"], cfg["ingest"]["model"])
    r = Retriever(searcher=lambda v, k: search(index_dir, name, v, k)[0])
    hits = r.retrieve(QUESTION, 3).hits
    return ", ".join(f"Article {h.article_number} ({h.score:.3f})" for h in hits)


def batch(args: list[str]) -> str:
    out = subprocess.run([sys.executable, "-m", "rag.ingest.batch", *args], cwd=ROOT, capture_output=True,
                         text=True, env={**__import__("os").environ, "LANGFUSE_TRACING_ENABLED": "false",
                                         "PYTHONPATH": str(ROOT / "src")})
    lines = out.stdout.strip().splitlines()  # the summary line; model-loading progress goes to stderr
    return lines[0] if lines else f"failed: {out.stderr.strip().splitlines()[-1]}"


with tempfile.TemporaryDirectory(prefix="batch-demo-") as tmp:
    tmp = Path(tmp)
    shutil.copytree(ROOT / cfg["ingest"]["index_dir"], tmp / "chroma")
    shutil.copy(ROOT / cfg["corpus"]["output"], tmp / "articles.json")
    doc = ROOT / "data/samples/batch_test_document.json"
    amended = tmp / "amended.json"
    records = json.loads(doc.read_text(encoding="utf-8"))
    records[0]["text_en"] += " This applies to contracts signed after 1 January 2027."
    amended.write_text(json.dumps(records, ensure_ascii=False), encoding="utf-8")
    common = ["--index-dir", str(tmp / "chroma"), "--corpus", str(tmp / "articles.json")]

    print("# Batch re-indexing test\n")
    print("Generated by `python scripts/batch_reindex_demo.py` on a temporary copy of the production index and "
          "corpus (the real ones are never touched). The new document, `data/samples/batch_test_document.json`, is a "
          "hypothetical Article 1150 on electronic signatures, clearly marked as test text, because the Civil Code "
          "has no such article: retrieval can only find it after the update.\n")
    print(f"Question used to check retrieval: *{QUESTION}*\n")
    print("| Step | Result |\n|---|---|")
    print(f"| 1. Top 3 before the update | {top3(tmp / 'chroma')} |")
    print(f"| 2. `python -m rag.ingest.batch data/samples/batch_test_document.json` | {batch([str(doc), *common])} |")
    print(f"| 3. Top 3 after the update | {top3(tmp / 'chroma')} |")
    print(f"| 4. Same file again | {batch([str(doc), *common])} |")
    print(f"| 5. Amended version of Article 1150 | {batch([str(amended), *common])} |")
    corpus = json.loads((tmp / "articles.json").read_text(encoding="utf-8"))
    print(f"| 6. Corpus file after the updates | {len(corpus):,} articles; Article 1150 present: "
          f"{any(a['article_number'] == 1150 for a in corpus)} |")
    print("\nOnly new or changed chunks are embedded; unchanged ones are skipped, so a re-run costs nothing. On the "
          "production index, record a batch update with `dvc commit` + `dvc push` (or rebuild with `dvc repro`).")
