#!/usr/bin/env bash
# R02 evidence: run the /health and /ask checks against a live API and print Markdown
# (each command, its HTTP status and body). Usage: scripts/curl_checks.sh > reports/curl_checks.md
BASE=${BASE:-http://localhost:8000}
run() {  # run <title> <command string>
  printf '### %s\n\n```console\n$ %s\n' "$1" "$2"
  eval "$2 -s -w '\nHTTP %{http_code}\n'"
  printf '```\n\n'
}
printf '# API checks (curl)\n\nGenerated by `scripts/curl_checks.sh` against %s on %s.\n\n' "$BASE" "$(date -u +%Y-%m-%dT%H:%MZ)"
run "Health" "curl $BASE/health"
run "Empty question → 422" "curl -X POST $BASE/ask -H 'Content-Type: application/json' -d '{\"question\": \"\"}'"
run "Whitespace-only question → 422" "curl -X POST $BASE/ask -H 'Content-Type: application/json' -d '{\"question\": \"   \"}'"
run "Missing question → 422" "curl -X POST $BASE/ask -H 'Content-Type: application/json' -d '{}'"
run "Arabic question" "curl -X POST $BASE/ask -H 'Content-Type: application/json' -d '{\"question\": \"ما حكم هبة الأموال المستقبلة؟\"}'"
run "English question" "curl -X POST $BASE/ask -H 'Content-Type: application/json' -d '{\"question\": \"At what age does a person reach legal majority?\"}'"
run "Out of scope: declines, no sources" "curl -X POST $BASE/ask -H 'Content-Type: application/json' -d '{\"question\": \"What is the penalty for theft?\"}'"
